org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true

mod_id=xray
mod_version=26.2.0.1
minecraft_version=26.2
minecraft_version_range=26.2,26.3

# NeoForge
neoforge_version=26.2.0.6-beta
neoforge_version_range=26.2.0.0-beta

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2

iris_version=7088024
