org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true

mod_id=xray
mod_version=26.2.0.0
minecraft_version=26.2
minecraft_version_range=26.1,26.2

# NeoForge
neoforge_version=26.1.0.17-beta
neoforge_version_range=26.1.0.0-beta

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.153.0+26.2

iris_version=7088024
