pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()

        maven { url = 'https://maven.fabricmc.net' }
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = "https://maven.nanite.dev/releases" }
    }
}

include("common", "neoforge", "fabric")
