modLoader="javafml" #required
loaderVersion="[4,)" #required
credits="ErrorMikey" #optional
authors="AdvancedXRay Team" #optional
license="GNU GPL v3.0 (https://github.com/MichaelHillcox/XRay-Mod/blob/master/LICENSE)"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
    modId="xray"
    version="${version}"
    displayName="Advanced XRay"
    description="An advanced XRay mod for Minecraft."

[[dependencies.xray]]
    modId="neoforge"
    required=true
    versionRange="[${forge_version_range},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.xray]]
    modId="minecraft"
    required=true
    versionRange="[${minecraft_version_range})"
    ordering="NONE"
    side="CLIENT"

[[mixins]]
config = 'xray.mixins.json'
